# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

# Copy only the necessary files and directories
COPY common/ /app/common/
COPY merge_service/ /app/merge_service/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r merge_service/requirements.txt

# Run app.py when the container launches
CMD ["python", "-m", "merge_service.merger"]