# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

# Copy only the necessary files and directories
COPY common/ /app/common/
COPY config/ /app/config/
COPY shared/ /app/shared/
COPY price_service/ /app/price_service/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r price_service/requirements.txt

# Define environment variable
ENV COINMARKET_API_KEY 'b8d1c1fe-625c-41be-b758-5d39dc8e55c2'

# Run app.py when the container launches
CMD ["python", "-m", "price_service.price_publisher"]